### ISSUE TITLE
Accessing environment variables

### ISSUE THREAD

**Issue by Treblesteph** [Treblesteph/oh-data-demo-template#3]
In original repo, they are all set in `settings.py`, then accessed from there sometimes, for example in `views.py` line 87/88: 

```python
context = {'client_id': settings.OH_CLIENT_ID,
                  'oh_proj_page': settings.OH_ACTIVITY_PAGE}
```
but sometimes they are reset in the file they are used from, for example, in `models.py` line 11/12:

```python
OH_CLIENT_ID = os.getenv('OH_CLIENT_ID', '')
OH_CLIENT_SECRET = os.getenv('OH_CLIENT_SECRET', '')
```

Is there a reason for accessing differently or should they all be set in `settings.py` and used from there?

**Comment by Treblesteph** [comment]
@madprime, @gedankenstuecke, @mcescalante

**Comment by gedankenstuecke** [comment]
I think this are artifacts of the development. For the uploader template I thus put all of them in a single place and always grab them from there. I’d recommend doing the same here. :)

**Comment by Treblesteph** [comment]
cool, thought so and just wanted to double check - thanks :)

**Comment by madprime** [comment]
Agree it looks like an artifact! Accessed from settings sounds ideal to me
